not sure why but including font-awesome as a dependency causes an error but including as devDependency works?
Cannot read property 'emberCliFontAwesome' of undefined
TypeError: Cannot read property 'emberCliFontAwesome' of undefined
    at Class.included (/code_js/ember-cli-table-pagination/node_modules/ember-cli-font-awesome/index.js:19:35)
    at /code_js/ember-cli-table-pagination/node_modules/ember-cli/lib/models/addon.js:241:32
    at Array.map (native)
    at Class.eachAddonInvoke (/code_js/ember-cli-table-pagination/node_modules/ember-cli/lib/models/addon.js:239:22)
    at Class.Addon.included (/code_js/ember-cli-table-pagination/node_modules/ember-cli/lib/models/addon.js:345:8)
    at EmberAddon.<anonymous> (/code_js/ember-cli-table-pagination/node_modules/ember-cli/lib/broccoli/ember-app.js:312:15)
    at Array.filter (native)
    at EmberAddon.EmberApp._notifyAddonIncluded (/code_js/ember-cli-table-pagination/node_modules/ember-cli/lib/broccoli/ember-app.js:307:45)
    at EmberAddon.EmberApp [as appConstructor] (/code_js/ember-cli-table-pagination/node_modules/ember-cli/lib/broccoli/ember-app.js:103:8)
    at new EmberAddon (/code_js/ember-cli-table-pagination/node_modules/ember-cli/lib/broccoli/ember-addon.js:26:8)